# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 20
# Issues with these labels will never be considered stale
exemptLabels:
  - "status: analysing"
  - "status: inNextRelease"
  - "status: inProgress"
  - "status: wontfix"
  - "type: enhancement"
# Label to use when marking an issue as stale
staleLabel: "status: markedForAutoClose"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked for closing, because it has not had
  activity in 90 days. It will be closed if no further activity occurs in 20 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
